version: '3.7'

services:
  php:
    build:
      context: ./php
      target: dev
      dockerfile: Dockerfile
    environment:
      - PHP_IDE_CONFIG=serverName=${DEBUG_SERVER_NAME}
      - XDEBUG_CONFIG=remote_host=${DEBUG_REMOTE_HOST} remote_port=${DEBUG_REMOTE_PORT} idekey=${DEBUG_IDEKEY}
    volumes:
      - ./../src:/var/www/html
#      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  scrape_worker:
    build:
      context: ./scrape_worker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./../:/var/www/code

  save_worker:
    build:
      context: ./save_worker
      target: dev
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mysql
    volumes:
      - ./../src:/var/www/html

  nginx:
    build:
      context: ./nginx
      target: dev
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./../src:/var/www/html

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    image: books-parsers-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 8080:15672