version: '3.7'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: books-parsers-php
    volumes:
      - ./../:/var/www/code/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: books-parsers-nginx
    ports:
      - 80:80
    volumes:
      - ./../:/var/www/code/
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
