version: '3.7'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: books-parsers-php

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: books-parsers-nginx
    ports:
      - 80:80